# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.

  config.vm.box="Centos65"
  config.vm.box_url='https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box'


  config.vm.define "puppetmaster" do |puppetmaster|
	  puppetmaster.vm.network "private_network",ip: "192.168.50.10",
	  virtualbox__init: "puppetmaster"
	  puppetmaster.vm.network "forwarded_port",guest: 80,host: 8080
	  puppetmaster.vm.network "forwarded_port",guest: 443,host: 8443
	  puppetmaster.vm.provision "shell", path: "../../bootstrap/puppetmaster.sh",args: ["Redhat"]
  end


end
